# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/safesign
spring.datasource.username=postgres
spring.datasource.password=ineza2008
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Groq Configuration
groq.api.key=your-groq-key-here
# Python executable - change to "python3" on Linux/Mac if needed
python.executable=python

# Server Configuration
server.port=8080
